import React, { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Button,
  EmptyState,
  Flex,
  Icon,
  Inline,
  LoadingSpinner,
  Panel,
  PanelBody,
  Select,
  Text,
  TextArea,
  useExtensionApi,
} from "@hubspot/ui-extensions";
import { specToMarkdown, specToTsx } from "../lib/exports.js";
import { createExportPanelService } from "../lib/exportPanelServices.js";
import { useProjects } from "../state/projects.jsx";
import { BACKEND_ENABLED, WORKER_URL } from "../config.js";
import { useEffectRunner } from "../hooks/useEffectRunner.js";
import { useStream } from "../hooks/useStream.js";

// Side panel that renders the current spec as JSON / Markdown / TSX starter.
// Markdown is model-generated by the worker and cached per spec hash; the
// panel fetches cached state on open and shows a Generate / Regenerate
// affordance rather than auto-calling the model. JSON and TSX are emitted
// locally (see lib/exports.js). Every format has a one-click copy button.
export const ExportPanel = ({ spec, projectId }) => {
  const [format, setFormat] = useState("markdown");
  const { auth } = useProjects();
  const { actions } = useExtensionApi();
  const { mountedRef, runTracked, startDetached } = useEffectRunner();

  // Backend-reported state of the markdown design doc.
  // { markdown, updated_at, spec_updated_at, stale, has_spec }
  const [docState, setDocState] = useState(null);
  const [docLoading, setDocLoading] = useState(false);
  const [genError, setGenError] = useState(null);
  const [docFetched, setDocFetched] = useState(false);

  // Streaming state. While a DO-backed generation is in flight, streamingId
  // drives useStream; chunks append to streamingMarkdown so the user watches
  // the doc being written. On done/error, both clear.
  const [streamingId, setStreamingId] = useState(null);
  const [streamingMarkdown, setStreamingMarkdown] = useState("");

  // Ref mirror so onDone reads the final buffer without a stale closure.
  const streamingMarkdownRef = React.useRef("");
  useEffect(() => {
    streamingMarkdownRef.current = streamingMarkdown;
  }, [streamingMarkdown]);

  useStream({
    workerUrl: WORKER_URL,
    streamId: streamingId,
    enabled: Boolean(streamingId),
    onChunk: (append) => {
      setStreamingMarkdown((prev) => prev + append);
    },
    onDone: (data) => {
      if (!mountedRef.current) return;
      setDocState((prev) => ({
        ...(prev ?? {}),
        markdown: streamingMarkdownRef.current,
        updated_at: data?.updatedAt ?? Date.now(),
        stale: false,
        has_spec: true,
      }));
      setStreamingId(null);
      setStreamingMarkdown("");
      setDocLoading(false);
    },
    onError: (err) => {
      if (!mountedRef.current) return;
      setGenError(err?.message ?? String(err));
      setStreamingId(null);
      setStreamingMarkdown("");
      setDocLoading(false);
    },
  });

  const canUseBackend = BACKEND_ENABLED && !!projectId;
  const exportPanelService = useMemo(
    () =>
      createExportPanelService({
        auth,
        projectId,
        mountedRef,
        runTracked,
        startDetached,
      }),
    [auth, mountedRef, projectId, runTracked, startDetached],
  );

  // Peek at cached doc state on open (no generation). A GET failure isn't
  // surfaced as an error — we fall through to the empty state, and the
  // explicit Generate click will produce a real error if the backend is
  // actually broken.
  useEffect(() => {
    return exportPanelService.startDocLoad({
      canUseBackend,
      docFetched,
      setDocLoading,
      setDocState,
      setDocFetched,
      setStreamingId,
      setStreamingMarkdown,
    });
  }, [canUseBackend, docFetched, exportPanelService]);

  const generate = async ({ regenerate = false } = {}) => {
    return exportPanelService.generateDesignDoc({
      canUseBackend,
      regenerate,
      setDocLoading,
      setGenError,
      setDocState,
      setStreamingMarkdown,
      setStreamingId,
    });
  };

  const { content, filename } = useMemo(() => {
    const baseName = slugify(spec?.meta?.name || "card");
    if (format === "json") {
      return {
        content: JSON.stringify(spec ?? {}, null, 2),
        filename: `${baseName}.json`,
      };
    }
    if (format === "tsx") {
      return { content: specToTsx(spec ?? {}), filename: `${baseName}.tsx` };
    }
    // While a generation is streaming, show the live buffer — gives the user
    // something to watch instead of a stale empty TextArea for ~30s.
    const body =
      (streamingId ? streamingMarkdown : null) ??
      docState?.markdown ??
      (canUseBackend ? "" : specToMarkdown(spec ?? {}));
    return { content: body, filename: `${baseName}.md` };
  }, [spec, format, docState, canUseBackend, streamingId, streamingMarkdown]);

  const hasSpec = canUseBackend ? docState?.has_spec !== false : !!spec;
  const hasDoc = !!docState?.markdown;

  const copy = () => {
    if (!content || !actions?.copyTextToClipboard) return;
    actions.copyTextToClipboard(content);
    actions.addAlert?.({
      title: "Copied to clipboard",
      message: filename,
      type: "success",
    });
  };

  const showEmptyNoSpec = !hasSpec && canUseBackend;
  const showMarkdownEmpty =
    format === "markdown" && canUseBackend && !hasDoc && !docLoading && !genError;

  return (
    <Panel id="export-panel" title="Export" width="md" variant="modal">
      <PanelBody>

        <Flex direction="column" gap="md">
          <Select
            label="Format"
            name="export-format"
            value={format}
            onChange={setFormat}
            options={[
              { label: "Design doc (Markdown)", value: "markdown" },
              { label: "Extension starter (TSX)", value: "tsx" },
              { label: "Raw spec (JSON)", value: "json" },
            ]}
          />

          {showEmptyNoSpec ? (
            <EmptyState title="No spec yet" layout="vertical">
              <Text>
                Chat with Studio to generate a card, then come back here
                to export a design doc, TSX starter, or raw spec.
              </Text>
            </EmptyState>
          ) : showMarkdownEmpty ? (
            <EmptyState title="No design doc yet" layout="vertical">
              <Text>
                Generate an implementation-ready design doc from your spec
                and chat history. The model writes sections for context,
                user stories, UI structure, state, data contract, and
                interactions.
              </Text>
              <Button
                variant="primary"
                disabled={docLoading}
                onClick={() => generate({ regenerate: false })}
              >
                {docLoading ? "Generating…" : "Generate design doc"}
              </Button>
            </EmptyState>
          ) : format === "markdown" && canUseBackend && docLoading && !hasDoc && !streamingId ? (
            <DesignDocSkeleton streamingMarkdown="" />
          ) : (
            <>
              {format === "markdown" && docState?.stale && (
                <Alert title="Spec has changed" variant="warning">
                  Your spec was updated after this design doc was
                  generated. Regenerate to pick up the latest changes.
                </Alert>
              )}
              {genError && (
                <Alert title="Generation failed" variant="danger">
                  {genError}
                </Alert>
              )}
              {!streamingId && (
                <Flex direction="row" gap="xs" align="center" justify="between">
                  <Text variant="microcopy">
                    {format === "markdown"
                      ? docLoading
                        ? "Generating…"
                        : docState?.updated_at
                          ? `Generated ${formatTimestamp(docState.updated_at)} · ${filename}`
                          : filename
                      : filename}
                  </Text>
                  <Inline gap="xs" alignment="center">
                    <Button size="xs" variant="secondary" onClick={copy} disabled={!content}>
                      Copy
                    </Button>
                    {format === "markdown" && (
                      <Button
                        size="xs"
                        variant={docState?.stale ? "primary" : "secondary"}
                        disabled={docLoading}
                        onClick={() => generate({ regenerate: true })}
                      >
                        {docLoading ? "…" : "Regenerate"}
                      </Button>
                    )}
                  </Inline>
                </Flex>
              )}
              {format === "markdown" && streamingId && (
                <DesignDocSkeleton streamingMarkdown={streamingMarkdown} />
              )}
              <TextArea
                label=""
                name="export-content"
                value={content}
                readOnly
                resize="vertical"
                rows={streamingId ? 10 : 18}
              />
            </>
          )}
        </Flex>

      </PanelBody>
    </Panel>
  );
};

// Sections the model writes, in order. Mirrors prompts/design_doc.md — if the
// prompt's section list changes, update this so the skeleton stays accurate.
const DOC_SECTIONS = [
  "Context",
  "User stories",
  "UI structure",
  "View modes & state",
  "Data contract",
  "Interactions",
  "Edge cases & open questions",
];

function getSectionProgress(streamingMarkdown) {
  const seen = new Set();
  let lastSeenIdx = -1;
  if (streamingMarkdown) {
    for (const line of streamingMarkdown.split("\n")) {
      const m = /^##\s+(.+?)\s*$/.exec(line);
      if (!m) continue;
      const heading = m[1].trim().toLowerCase();
      const idx = DOC_SECTIONS.findIndex((s) => s.toLowerCase() === heading);
      if (idx >= 0) {
        seen.add(idx);
        lastSeenIdx = idx;
      }
    }
  }
  // Before the first ## lands, the model is writing the H1 / opening — show
  // Context as the active section so the skeleton isn't all-pending.
  const current = lastSeenIdx === -1 ? 0 : lastSeenIdx;
  return { current, seen };
}

const DesignDocSkeleton = ({ streamingMarkdown }) => {
  const { current, seen } = getSectionProgress(streamingMarkdown);
  return (
    <Flex direction="column" gap="xs">
      <Text variant="microcopy">Generating design doc…</Text>
      {DOC_SECTIONS.map((label, idx) => {
        const isCurrent = idx === current;
        const isDone = seen.has(idx) && !isCurrent;
        return (
          <Inline key={label} gap="xs" alignment="center">
            {isCurrent ? (
              <LoadingSpinner size="xs" />
            ) : isDone ? (
              <Icon name="success" size="xs" />
            ) : (
              <Icon name="circleHollow" size="xs" />
            )}
            <Text variant={isDone || isCurrent ? undefined : "microcopy"}>
              {label}
            </Text>
          </Inline>
        );
      })}
    </Flex>
  );
};

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "card";
}

function formatTimestamp(ms) {
  try {
    const d = new Date(ms);
    return d.toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  } catch {
    return "just now";
  }
}
